services:
- type: web
  name: dashboard
  env: python
  plan: free
  buildCommand: |
    pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: gunicorn  --chdir src app:server
  envVars:
  - key: FLASK_ENV
    value: production
